### ISSUE TITLE
How to define transparent in targetColor or replaceColor?

### ISSUE THREAD

**Issue by iamjoyce** [turakvlad/replace-color#1]
`type: rgb` Alpha is not supported so transparent color can't be defined.

`type: hex` Based on [this stackoverflow answer](https://stackoverflow.com/a/23201304/804702), transparent hex code is `#AARRGGBB`, but it's an invalid parameter.

```
{ ReplaceColorError: Parameter is not valid
    at Promise (node_modules\replace-color\src\replace-color.js:32:23)
    at new Promise (<anonymous>)
    at module.exports (node_modules\replace-color\src\replace-color.js:20:10)
    (truncated)
  name: 'ReplaceColorError',
  code: 'PARAMETER_INVALID',
  field: 'options.colors.targetColor' }
```

Is there a way to use transparent as one of the parameter? Thank you

**Comment by turakvlad** [comment]
@iamjoyce, hi!

A package does not support transparent colors at present. I will try to add this feature as soon as possible.

**Comment by turakvlad** [comment]
@iamjoyce, hey once again.

Could you please help me with an API for this feature?

I'm thinking about adding a `transparent` option as one of the possible values for a `replaceColor` variable. If you want to replace a `targetColor` with a fully transparent one, you should use `replaceColor: 'transparent'`. In this case, you're able to use either `hex` or `rgb` types.

```js
const replaceColor = require('replace-color')

replaceColor({
  image: 'https://i.imgur.com/aCxZpaq.png',
  colors: {
    type: 'rgb', // Can be either `hex` or `rgb`.
    targetColor: [102,174,116], // Can be either `hex` or `rgb`.
    replaceColor: 'transparent'
  },
  deltaE: 10
})
  .then((jimpObject) => {
    jimpObject.write('./output.png', (err) => {
      if (err) return console.log(err)
    })
  })
  .catch((err) => {
    console.log(err)
  })
```

The output:
![output](https://user-images.githubusercontent.com/7996184/46658536-3d21a600-cbb3-11e8-8ee5-d38ffe7be58d.png)

If you want to have not a fully transparent color, you can use the fourth item in a `replaceColor` variable to specify an alpha - `[0, 1]`. In this case, you can use `rgb` type only.

Let's assume that we want to replace a green color with the same green color but with 50% transparency.

```js
const replaceColor = require('replace-color')

replaceColor({
  image: 'https://i.imgur.com/aCxZpaq.png',
  colors: {
    type: 'rgb', // Must be `rgb`.
    targetColor: [102,174,116], // Must be `rgb`.
    replaceColor: [102,174,116, 0.5]
  },
  deltaE: 10
})
  .then((jimpObject) => {
    jimpObject.write('./output.png', (err) => {
      if (err) return console.log(err)
    })
  })
  .catch((err) => {
    console.log(err)
  })
```

The output:
![output](https://user-images.githubusercontent.com/7996184/46658755-bcaf7500-cbb3-11e8-8f6c-d3c60910a502.png)

What do you think about this? To my mind, this API is not the most obvious one. Do you have any suggestions? Maybe, we should support transparent `hex` codes too (e.g. `#AARRGGBB`)?

In this case, we will be able to have not a fully transparent color with `hex` too.

A `targetColor` variable can be:
- a `transparent` string for `hex` and `rgb` types;
- an array of for items where the fourth item defines an alpha (`[0, 1]`) - `[102,174,116, 0.5]` for `rgb` type;
- a transparent `hex` code where transparency is controlled by the alpha channel (`AA` in `#AARRGGBB`) for `hex` type.

If we go this way, an API will be more obvious. Also, I don't think that we need to have an ability to define transparent colors for a `targetColor` (mainly this color will be selected with a color picker or something like that). What do you think?

**Comment by iamjoyce** [comment]
@turakvlad Thank you! 

> What do you think about this? To my mind, this API is not the most obvious one. Do you have any suggestions? Maybe, we should support transparent hex codes too (e.g. #AARRGGBB)?

I think using `transparent` string and 4 elements `rgb` array as input seems pretty clear. Though I think `rgb` might have to rename to `rgba` to be more intuitive.

For `hex` code, are other alpha hex supported? For example `#00ff0080`.
* If yes, I think for consistency sake, it makes sense to support a transparent hex code.
* If no, I think it's better to leave it as (perhaps) a future enhancement otherwise it's misleading to just support a transparent `hex` code.

> The output

Is it possible to have smoother and cleaner edges? 

> Also, I don't think that we need to have an ability to define transparent colors for a `targetColor` (mainly this color will be selected with a color picker or something like that). What do you think?

On a contrary, I think it's necessary for `targetColor`. It's very natural for devs to assume that since `replaceColor` supports (e.g.) rgba = `targetColor` also supports rgba.

Actually I found this library from [https://github.com/oliver-moran/jimp/issues/316](https://github.com/oliver-moran/jimp/issues/316) - which was an issue to ask how to replace transparency with a colour. On a personal level, I will definitely need this feature 😸 

Hopefully my comments of some help to you. Thanks again for your help!

**Comment by turakvlad** [comment]
@iamjoyce, thank you for your comment. It helps me a lot!

> For hex code, are other alpha hex supported? For example #00ff0080.

Yes, it will be possible to support the whole alpha hex range - `[AA, FF]` (i.e., from `0` to `255`). 

> If yes, I think for consistency sake, it makes sense to support a transparent hex code.

I agree with you. I will add support for a transparent hex code.

> Is it possible to have smoother and cleaner edges?

I think you should play with a `deltaE` value. 

> On a contrary, I think it's necessary for targetColor. It's very natural for devs to assume that since replaceColor supports (e.g.) rgba = targetColor also supports rgba.

The problem here is that the library is using the [deltaE](http://zschuessler.github.io/DeltaE/learn/) algorithm to calculate the difference between two colors. These two colors must be in a [`lab`](https://en.wikipedia.org/wiki/CIELAB_color_space) color space. I am using a [`color-convert`](https://www.npmjs.com/package/color-convert) package to convert colors from `hex` or `rgb` to `lab`. `lab` color space doesn't have someething like alpha (as I know). So, it looks like it's not possible to convert `rgba` or `ahex` (let's call it this way) to `lab`.

Thank you once again!

**Comment by turakvlad** [comment]
@iamjoyce, hey!

I have just released [v2.0.0](https://www.npmjs.com/package/replace-color). Would you mind please to check it out? Does it satisfy your needs? 

Thanks.

**Comment by turakvlad** [comment]
@iamjoyce, hi. I hope it works for you. I am going to close this issue. If something is wrong, jut re-open it again. Thanks!

**Comment by andrewhawk1ns** [comment]
How do you specify transparent for a target color ? I need to change transparency in a png to white

I noticed in the code that replace color supports transparency but target color does not
