### ISSUE TITLE
Not compatible with latest jimp version (0.5.3)

### ISSUE THREAD

**Issue by janikga** [turakvlad/replace-color#2]
Hey guys,

I've been trying to replace colors for an image using this library and then using jimp (`0.5.3`) to composite different images together.

my code:
```ts
  const transformedImage = await replaceColor({
        image: jimpObject | imagePath,
        colors: {
          targetColor,
          replaceColor: desiredColor,
          type: 'hex'
        }
      })
```

I encountered two errors:

1. When the `image` parameter was the path to the image, transforming worked, but in the step where I did `someJimpInstance.composite(transformedImage)`, `jimp` was complaining that `transformedImage` wasn't a valid jimp instance, even though the `instanceof Jimp` test was true.

2. When using a `jimpObject` as a value for the `image` parameter, `replaceColor` threw this error: `No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.`, even though the `jimpObject ` was a valid jimp object.

Downgrading to jimp `0.3.11` solved the problems for me.

**Comment by turakvlad** [comment]
Hey, @jagaSto.

Thanks for the information. I will update Jimp to the latest version in a few days. I will let you know when I do this.

**Comment by turakvlad** [comment]
@jagaSto,

I've just updated Jimp version to **0.5.3**. The **1.0.4** version is available on [NPM](https://www.npmjs.com/package/replace-color). Please, try this version and let me know whether it works or not.

Thanks.

**Comment by janikga** [comment]
Hey @turakvlad, 

sorry for the late response! I can confirm that it works with the latest version! Thank you 👍

**Comment by turakvlad** [comment]
@jagaSto, thanks! By the way, the [v2.0.0](https://www.npmjs.com/package/replace-color) was released a few minutes ago. I would highly recommend you to update the package. You will be able to replace a target color with a transparent one.
