### ISSUE TITLE
Removing colour from text

### ISSUE THREAD

**Issue by bknill** [turakvlad/replace-color#3]
Hey, 

Great library. 

I'm trying to remove the green from this image. 

![_hotspot_1267_87a1eb10-f1f4-11e8-a55f-1d333c2d6ce0](https://user-images.githubusercontent.com/7074483/50748360-00db1000-129e-11e9-8d9f-a2b48d9916e7.png)
![hotspot_1267_87a1eb10-f1f4-11e8-a55f-1d333c2d6ce0](https://user-images.githubusercontent.com/7074483/50748361-00db1000-129e-11e9-8663-cb12dcb28127.png)

Here is my code

 replaceColor({
          image: dir + '/' + image.src,
          colors: {
            type: 'hex',
            targetColor: '#00ff00',
            replaceColor: '#00000000',
            deltaE: 20
          }
        })

I'm still getting a green tinge around the letters. 

Do you know how I can completely remove all the green?

**Comment by turakvlad** [comment]
Hello, @bknill!

I am sorry for such a late response. 

Did you try to remove these green colors in a few iterations? I mean that you can try to remove a light green at first (you've already done this), and after that, you can run the second iteration to remove that darker green around the letters. These colors are very different: a lighter green and a darker one. I don't think that you will be able to remove them both in one iteration (even playing with `deltaE` won't help in this case, to my mind).

Please, let me know when you try. If it does not help, we can think about some other ways.

**Comment by turakvlad** [comment]
I am going to close this issue due to inactivity. If you have any questions, let me know.
